parameters:
  configuration: 'Release'
  platform: ''
  additionalBuildArguments: '-m'

jobs:
- job: Build${{ parameters.platform }}${{ parameters.configuration }}
  displayName: Build ${{ parameters.platform }} ${{ parameters.configuration }}
  variables:
    BuildConfiguration: ${{ parameters.configuration }}
    BuildPlatform: ${{ parameters.platform }}
  pool:
    ${{ if eq(variables['System.CollectionUri'], 'https://dev.azure.com/ms/') }}:
      name: 'windows-2019'
    ${{ if ne(variables['System.CollectionUri'], 'https://dev.azure.com/ms/') }}:
      name: 'windows-2019'
  timeoutInMinutes: 120
  strategy:
    maxParallel: 10
  steps:
  - template: build-powertoys-steps.yml
    parameters:
      additionalBuildArguments: ${{ parameters.additionalBuildArguments }}
